package seeder

// Frontend permission catalog codegen. The `cmd/gen-frontend-permissions`
// binary calls RenderFrontendPermissions to produce
// `web/src/generated/permissions.ts`; the drift-guard test
// (frontend_permissions_test.go) calls the same function in-memory and
// asserts byte-equality with the on-disk file.
//
// Output shape is two disjoint string-literal unions partitioned by the
// `scope` field in seeds/permissions.yaml:
//
//   - `OrganizationScope` — every YAML entry with `scope: organization`.
//     Consumed by `useHasOrganizationAccess` (org-tier check).
//   - `ProjectScope` — every YAML entry with `scope: project`. Consumed
//     by `useHasProjectAccess` (project-tier check, additively resolved).
//
// Mirrors Langfuse's production pattern (organizationScopes /
// projectScopes in competitors/langfuse/web/src/features/rbac/constants/).
// Tier is encoded in WHICH union the verb belongs to, not a runtime
// `scope_level` discriminator — the type system rejects wrong-tier checks
// at compile time. See CLAUDE.md 2026-04-30 (project-rbac).
//
// Keeping the render logic in this package (not in the binary's
// `package main`) makes it importable from tests — the standard Go
// pattern for "binary + library that share rendering code."

import (
	"bytes"
	"fmt"
	"sort"
)

// RenderFrontendPermissions emits the TS file body for the supplied
// permission seeds. Output is deterministic (entries sorted by name)
// so two invocations with the same input produce byte-identical bytes.
func RenderFrontendPermissions(perms []PermissionSeed) []byte {
	sorted := make([]PermissionSeed, len(perms))
	copy(sorted, perms)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var orgPerms, projectPerms []PermissionSeed
	for _, p := range sorted {
		// Default missing/empty `scope` to organization (matches the
		// seeder's existing default; should never happen in well-formed
		// YAML because TestPermissionScopesMatchRoutes asserts every
		// permission carries a known scope).
		switch p.Scope {
		case "project":
			projectPerms = append(projectPerms, p)
		default:
			orgPerms = append(orgPerms, p)
		}
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by `go run ./cmd/gen-frontend-permissions`. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Source of truth: seeds/permissions.yaml\n")
	b.WriteString("// Regenerate via `make gen-frontend-permissions` (or `make generate`).\n")
	b.WriteString("//\n")
	b.WriteString("// Two disjoint scope unions — tier is encoded in the type itself, not\n")
	b.WriteString("// a runtime `scope_level` field. `useHasOrganizationAccess` accepts\n")
	b.WriteString("// `OrganizationScope`; `useHasProjectAccess` accepts `ProjectScope`.\n")
	b.WriteString("// Passing a wrong-tier scope is a TypeScript error.\n")
	b.WriteString("//\n")
	b.WriteString("// Editing this file by hand will be reverted by the next codegen run.\n")
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * Org-tier scope. Resolves against the user's organization role only;\n")
	b.WriteString(" * project_members grants do NOT affect org-tier permissions.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Use with `useHasOrganizationAccess` from\n")
	b.WriteString(" * `@/hooks/rbac/use-has-organization-access`.\n")
	b.WriteString(" */\n")
	writeUnion(&b, "OrganizationScope", orgPerms)
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * Project-tier scope. Resolved additively: the org role's project-tier\n")
	b.WriteString(" * projection UNIONs with any project_members grant. Per-resource grants\n")
	b.WriteString(" * only ADD permissions, never reduce. `projectId` is required.\n")
	b.WriteString(" *\n")
	b.WriteString(" * Use with `useHasProjectAccess` from\n")
	b.WriteString(" * `@/hooks/rbac/use-has-project-access`.\n")
	b.WriteString(" */\n")
	writeUnion(&b, "ProjectScope", projectPerms)
	b.WriteString("\n")

	b.WriteString("/**\n")
	b.WriteString(" * Tier-agnostic scope union — every permission in the catalog regardless\n")
	b.WriteString(" * of tier. Reserved for code that legitimately doesn't know the tier at\n")
	b.WriteString(" * type-construction time (e.g., navigation route metadata where a route\n")
	b.WriteString(" * can be guarded by either an org-tier OR project-tier scope).\n")
	b.WriteString(" *\n")
	b.WriteString(" * Prefer `OrganizationScope` or `ProjectScope` directly. Use this only\n")
	b.WriteString(" * at boundaries that span both tiers.\n")
	b.WriteString(" */\n")
	b.WriteString("export type Scope = OrganizationScope | ProjectScope\n")

	return b.Bytes()
}

func writeUnion(b *bytes.Buffer, name string, perms []PermissionSeed) {
	if len(perms) == 0 {
		// Type-system carve-out: an empty union would be `never`, which
		// breaks consumers. In practice the YAML always has entries on
		// both sides, but emit a safe placeholder if the catalog is ever
		// reshaped to be one-tier.
		b.WriteString(fmt.Sprintf("export type %s = never\n", name))
		return
	}
	b.WriteString(fmt.Sprintf("export type %s =\n", name))
	for i, p := range perms {
		sep := "|"
		if i == 0 {
			sep = " "
		}
		b.WriteString(fmt.Sprintf("  %s '%s'\n", sep, p.Name))
	}
}
