version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hashirventhodi"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "deps(go)"
      include: "scope"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "hashirventhodi"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "deps(docker)"

  # NPM (Frontend)
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "hashirventhodi"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "deps(npm)"
      include: "scope"
    versioning-strategy: increase

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "11:00"
    open-pull-requests-limit: 2
    reviewers:
      - "hashirventhodi"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "deps(actions)"