name: Bug Report
description: File a bug report
title: "bug: <short description>"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug, and what you expected to happen when you encountered it.
      placeholder: Describe what went wrong and what you expected to happen...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe how to reproduce the bug. Please provide detailed steps, code snippets, configuration details, etc.
      placeholder: |
        1. Configure gateway with...
        2. Send request to...
        3. Observe error...
    validations:
      required: true
  - type: dropdown
    id: deployment-type
    attributes:
      label: Brokle Cloud or self-hosted?
      description: Select your deployment type
      options:
        - Brokle Cloud
        - Self-hosted
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version (if self-hosted)
      description: What version are you running? We may ask you to upgrade to the latest version, as many issues are continuously being fixed.
      placeholder: v1.2.3
    validations:
      required: false
  - type: textarea
    id: integration-versions
    attributes:
      label: SDK and integration versions
      description: If you're experiencing an issue with an integration or SDK, please share all package versions you're using. Include client libraries, API versions, etc.
      placeholder: |
        - Brokle Go SDK: v1.x.x
        - OpenAI client: v1.x.x
        - other relevant packages...
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Add any other information related to the bug here, including logs, screenshots, configuration files, etc.
      placeholder: Any additional context, error logs, screenshots...
    validations:
      required: false