-- ===================================
-- REPLACE KEY_ID WITH KEY_HASH
-- ===================================
-- Remove redundant key_id column and rename secret_hash to key_hash
-- key_hash now stores bcrypt hash of FULL API key (not just secret)
-- Format: bcrypt(bk_proj_{project_id}_{secret})

-- Step 1: Rename secret_hash to key_hash
ALTER TABLE api_keys RENAME COLUMN secret_hash TO key_hash;

-- Step 2: Drop old indexes
DROP INDEX IF EXISTS idx_api_keys_secret_hash;
DROP INDEX IF EXISTS idx_api_keys_key_id;

-- Step 3: Drop key_id column
ALTER TABLE api_keys DROP COLUMN IF EXISTS key_id;

-- Step 4: Create unique index on key_hash
CREATE UNIQUE INDEX idx_api_keys_key_hash ON api_keys(key_hash);

-- Step 5: Add comment
COMMENT ON COLUMN api_keys.key_hash IS 'Bcrypt hash of full API key (bk_proj_{project_id}_{secret})';

-- NOTE: Existing API keys will need to be regenerated by users
-- The old keys cannot be migrated because we only have hash of secret portion, not full key
