/**
 * Dashboards Feature
 */

// Types
export type {
  WidgetType,
  WidgetViewType,
  FilterOperator,
  QueryFilter,
  TimeRange,
  RelativeTimeRange,
  WidgetQuery,
  Widget,
  LayoutItem,
  Variable,
  VariableType,
  VariableValues,
  VariableQueryConfig,
  DashboardConfig,
  Dashboard,
  DashboardListItem,
  CreateDashboardRequest,
  UpdateDashboardRequest,
  DashboardListResponse,
  DashboardFilter,
  QueryExecutionParams,
  QueryMetadata,
  WidgetQueryResult,
  DashboardQueryResults,
  MeasureDefinition,
  DimensionDefinition,
  ViewDefinition,
  ViewDefinitionsResponse,
  TemplateCategory,
  DashboardTemplate,
  CreateFromTemplateRequest,
  DuplicateDashboardRequest,
  DashboardExport,
  DashboardImportRequest,
  ReactGridLayoutItem,
} from './types'

// Hooks
export {
  dashboardQueryKeys,
  useDashboardsQuery,
  useDashboardQuery,
  useCreateDashboardMutation,
  useUpdateDashboardMutation,
  useDeleteDashboardMutation,
  useLockDashboardMutation,
  useUnlockDashboardMutation,
  useImportDashboardMutation,
  useProjectDashboards,
  widgetQueryKeys,
  useDashboardQueries,
  useWidgetQuery,
  useRefreshDashboardQueries,
  useViewDefinitions,
  templateQueryKeys,
  useTemplatesQuery,
  useTemplateQuery,
  useCreateFromTemplateMutation,
  variableQueryKeys,
  useDashboardVariables,
  useDashboardTimeRange,
  useAutoSave,
  getAutoSaveStatusLabel,
  type AutoSaveStatus,
} from './hooks'

// Components
export {
  DashboardsTable,
  DashboardDetail,
  DashboardGrid,
  DashboardEditorToolbar,
  DashboardForm,
  CreateDashboardDialog,
  TemplateSelector,
  VariablesBar,
  AutoSaveIndicator,
  AutoRefreshControl,
  useAutoRefresh,
  ImportDashboardDialog,
  WidgetForm,
  WidgetEditDialog,
  AddWidgetButton,
  WidgetPalette,
  WIDGET_TYPES,
  type WidgetTypeDefinition,
  WidgetErrorBoundary,
  WidgetErrorFallback,
  WidgetRenderer,
  StatWidget,
  TimeSeriesWidget,
  TableWidget,
  BarWidget,
  PieWidget,
  HeatmapWidget,
  HistogramWidget,
  TraceListWidget,
  TextWidget,
  type StatData,
  type TimeSeriesData,
  type TableData,
  type ColumnDefinition,
  type BarData,
  type PieData,
  type HeatmapData,
  type HistogramData,
  type HistogramStats,
  type TraceListData,
  type TraceListItem,
  type TextData,
  StatSkeleton,
  TimeSeriesSkeleton,
  BarSkeleton,
  PieSkeleton,
  TableSkeleton,
  HeatmapSkeleton,
  HistogramSkeleton,
  TraceListSkeleton,
  TextSkeleton,
  GenericWidgetSkeleton,
  getWidgetSkeleton,
  WidgetSkeletonRenderer,
  QueryBuilder,
  ViewSelector,
  MeasureSelector,
  DimensionSelector,
  QueryPreview,
} from './components'

// API
export {
  getDashboards,
  getDashboardById,
  createDashboard,
  updateDashboard,
  deleteDashboard,
  duplicateDashboard,
  lockDashboard,
  unlockDashboard,
  exportDashboard,
  importDashboard,
} from './api/dashboards-api'

export {
  getTemplates,
  getTemplateById,
  createFromTemplate,
} from './api/templates-api'

export {
  executeDashboardQueries,
  executeWidgetQuery,
  getViewDefinitions,
} from './api/widget-queries-api'

// Utils
export {
  buildFilterFromDataPoint,
  buildFiltersFromDataPoint,
  encodeFiltersForUrl,
  buildDrilldownUrl,
  createDrilldownHandler,
  type DrilldownFilter,
  type DrilldownContext,
} from './utils'
