# Development Seed Data
# This file contains comprehensive test data for development and testing

organizations:
  - name: "Brokle Technologies"
    slug: "brokle-tech"
    billing_email: "billing@brokle.ai"
    plan: "enterprise"
    subscription_status: "active"
  
  - name: "Demo Organization"
    slug: "demo-org"
    billing_email: "demo@example.com"
    plan: "pro"
    subscription_status: "active"
  
  - name: "Test Startup"
    slug: "test-startup"
    billing_email: "test@startup.com"
    plan: "free"
    subscription_status: "active"

users:
  - email: "admin@brokle.ai"
    first_name: "Admin"
    last_name: "User"
    password: "admin123"
    email_verified: true
    is_active: true
    timezone: "UTC"
    language: "en"
  
  - email: "developer@brokle.ai"
    first_name: "Developer"
    last_name: "User"
    password: "dev123"
    email_verified: true
    is_active: true
    timezone: "America/New_York"
    language: "en"
  
  - email: "demo@example.com"
    first_name: "Demo"
    last_name: "User"
    password: "demo123"
    email_verified: true
    is_active: true
    timezone: "UTC"
    language: "en"

  - email: "test@startup.com"
    first_name: "Test"
    last_name: "User"
    password: "test123"
    email_verified: false
    is_active: true
    timezone: "UTC"
    language: "en"

rbac:
  permissions:
    # Organization permissions
    - name: "organizations:read"
      description: "View organization details and settings"
    
    - name: "organizations:write"
      description: "Create and update organizations"

    - name: "organizations:delete"
      description: "Delete organizations"

    - name: "organizations:admin"
      description: "Advanced organization administration"

    # Project permissions
    - name: "projects:read"
      description: "View projects and their details"

    - name: "projects:write"
      description: "Create and update projects"

    - name: "projects:delete"
      description: "Delete projects"

    # API Key permissions
    - name: "api-keys:read"
      description: "View API keys (excluding full values)"

    - name: "api-keys:write"
      description: "Create and update API keys"

    - name: "api-keys:delete"
      description: "Delete API keys"
    
    # Analytics permissions
    - name: "analytics:read"
      description: "View analytics and metrics"
    
    # Member permissions
    - name: "members:read"
      description: "View organization members"

    - name: "members:invite"
      description: "Invite new members to organization"

    - name: "members:remove"
      description: "Remove members from organization"
    
    # Role and permission management
    - name: "roles:read"
      description: "View roles and their permissions"

    - name: "roles:write"
      description: "Create and update custom roles"

    - name: "roles:delete"
      description: "Delete custom roles"
    
    - name: "permissions:read"
      description: "View available permissions"
    
    # Settings management
    - name: "settings:read"
      description: "View organization settings"
    
    - name: "settings:write"
      description: "Update organization settings"
    
    - name: "settings:export"
      description: "Export organization settings"
    
    - name: "settings:import"
      description: "Import organization settings"
    
    - name: "settings:admin"
      description: "Advanced settings management"

    # Admin permissions
    - name: "admin:manage"
      description: "Administrative access to platform management"

  roles:
    # Organization role templates (available to ALL organizations)
    - name: "owner"
      description: "Full access to organization and all its resources"
      scope_type: "organization"
      permissions:
        - "organizations:read"
        - "organizations:write"
        - "organizations:delete"
        - "organizations:admin"
        - "projects:read"
        - "projects:write"
        - "projects:delete"
        - "api-keys:read"
        - "api-keys:write"
        - "api-keys:delete"
        - "analytics:read"
        - "members:read"
        - "members:invite"
        - "members:remove"
        - "roles:read"
        - "roles:write"
        - "roles:delete"
        - "permissions:read"
        - "settings:read"
        - "settings:write"
        - "settings:export"
        - "settings:import"
        - "settings:admin"
    
    - name: "admin"
      description: "Administrative access to organization resources"
      scope_type: "organization"
      permissions:
        - "organizations:read"
        - "organizations:write"
        - "projects:read"
        - "projects:write"
        - "api-keys:read"
        - "api-keys:write"
        - "analytics:read"
        - "members:read"
        - "members:invite"
        - "roles:read"
        - "roles:write"
        - "permissions:read"
        - "settings:read"
        - "settings:write"
    
    - name: "developer"
      description: "Development access to projects and API keys"
      scope_type: "organization"
      permissions:
        - "organizations:read"
        - "projects:read"
        - "projects:write"
        - "api-keys:read"
        - "api-keys:write"
        - "analytics:read"
    
    - name: "viewer"
      description: "Read-only access to organization resources"
      scope_type: "organization"
      permissions:
        - "organizations:read"
        - "projects:read"
        - "api-keys:read"
        - "analytics:read"

  memberships:
    # Organization memberships with single roles
    - user_email: "admin@brokle.ai"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "brokle-tech"
    
    - user_email: "developer@brokle.ai"
      role_name: "developer"
      scope_type: "organization"
      organization_slug: "brokle-tech"
    
    - user_email: "demo@example.com"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "demo-org"
    
    - user_email: "test@startup.com"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "test-startup"

projects:
  - name: "AI Gateway"
    description: "Primary AI gateway and routing service"
    organization_slug: "brokle-tech"
    environments:
      - name: "Development"
        slug: "dev"
      - name: "Staging"
        slug: "staging"
      - name: "Production"
        slug: "prod"
  
  - name: "Analytics Platform"
    description: "AI analytics and observability platform"
    organization_slug: "brokle-tech"
    environments:
      - name: "Development"
        slug: "dev"
      - name: "Production"
        slug: "prod"
  
  - name: "Demo Application"
    description: "Demo application showcasing Brokle capabilities"
    organization_slug: "demo-org"
    environments:
      - name: "Demo"
        slug: "demo"
      - name: "Production"
        slug: "prod"

  - name: "Test Project"
    description: "Simple test project for validation"
    organization_slug: "test-startup"
    environments:
      - name: "Test"
        slug: "test"

api_keys:
  - name: "Development API Key"
    organization_slug: "brokle-tech"
    project_name: "AI Gateway"
    environment_name: "Development"
    rate_limit_per_minute: 1000
    rate_limit_per_hour: 10000
    rate_limit_per_day: 100000
    scopes:
      - "ai:completions"
      - "ai:embeddings"
      - "analytics:read"
    allowed_ips: []
  
  - name: "Production API Key"
    organization_slug: "brokle-tech"
    project_name: "AI Gateway"
    environment_name: "Production"
    rate_limit_per_minute: 5000
    rate_limit_per_hour: 50000
    rate_limit_per_day: 1000000
    scopes:
      - "ai:completions"
      - "ai:embeddings"
      - "analytics:read"
    allowed_ips: ["203.0.113.0/24", "198.51.100.0/24"]
  
  - name: "Demo API Key"
    organization_slug: "demo-org"
    project_name: "Demo Application"
    environment_name: "Demo"
    rate_limit_per_minute: 100
    rate_limit_per_hour: 1000
    rate_limit_per_day: 10000
    scopes:
      - "ai:completions"
    allowed_ips: []

  - name: "Test API Key"
    organization_slug: "test-startup"
    project_name: "Test Project"
    environment_name: "Test"
    rate_limit_per_minute: 60
    rate_limit_per_hour: 500
    rate_limit_per_day: 5000
    scopes:
      - "ai:completions"
    allowed_ips: []

onboarding_questions:
  - step: 1
    question_type: "single_choice"
    title: "What's your primary role?"
    description: "This helps us customize your experience"
    is_required: true
    options:
      - "Developer"
      - "Product Manager"
      - "Data Scientist"
      - "DevOps Engineer"
      - "CEO/Founder"
      - "Other"
    display_order: 1
    is_active: true
  
  - step: 2
    question_type: "multiple_choice"
    title: "Which AI providers do you currently use?"
    description: "Select all that apply"
    is_required: true
    options:
      - "OpenAI"
      - "Anthropic"
      - "Google AI"
      - "Cohere"
      - "Hugging Face"
      - "Azure OpenAI"
      - "AWS Bedrock"
      - "None yet"
    display_order: 2
    is_active: true
  
  - step: 3
    question_type: "single_choice"
    title: "What's your organization size?"
    description: "Help us understand your team"
    is_required: true
    options:
      - "Just me"
      - "2-10 people"
      - "11-50 people"
      - "51-200 people"
      - "200+ people"
    display_order: 3
    is_active: true
  
  - step: 4
    question_type: "text"
    title: "What's your primary use case for AI?"
    description: "Tell us about your main AI application (optional)"
    is_required: false
    options: []
    display_order: 4
    is_active: true
  
  - step: 5
    question_type: "single_choice"
    title: "How did you hear about Brokle?"
    description: "Help us improve our outreach"
    is_required: false
    options:
      - "Search engine"
      - "Social media"
      - "Word of mouth"
      - "Conference/Event"
      - "Blog/Article"
      - "GitHub"
      - "Other"
    display_order: 5
    is_active: true