# Development Seed Data
# Updated for Scope-Based RBAC System (60+ granular scopes)

organizations:
  - name: "Brokle Technologies"
    slug: "brokle-tech"
    billing_email: "billing@brokle.ai"
    plan: "enterprise"
    subscription_status: "active"

  - name: "Demo Organization"
    slug: "demo-org"
    billing_email: "demo@example.com"
    plan: "pro"
    subscription_status: "active"

  - name: "Test Startup"
    slug: "test-startup"
    billing_email: "test@startup.com"
    plan: "free"
    subscription_status: "active"

users:
  - email: "admin@brokle.ai"
    first_name: "Admin"
    last_name: "User"
    password: "admin123"
    email_verified: true
    is_active: true
    timezone: "UTC"
    language: "en"

  - email: "developer@brokle.ai"
    first_name: "Developer"
    last_name: "User"
    password: "dev123"
    email_verified: true
    is_active: true
    timezone: "America/New_York"
    language: "en"

  - email: "demo@example.com"
    first_name: "Demo"
    last_name: "User"
    password: "demo123"
    email_verified: true
    is_active: true
    timezone: "UTC"
    language: "en"

  - email: "test@startup.com"
    first_name: "Test"
    last_name: "User"
    password: "test123"
    email_verified: false
    is_active: true
    timezone: "UTC"
    language: "en"

rbac:
  permissions:
    # ========================================
    # ORGANIZATION-LEVEL SCOPES (40 scopes)
    # ========================================

    # Organization Management (4 scopes)
    - name: "organizations:read"
      description: "View organization details and settings"
    - name: "organizations:write"
      description: "Create and update organizations"
    - name: "organizations:delete"
      description: "Delete organizations"
    - name: "organizations:admin"
      description: "Advanced organization administration"

    # Members Management (5 scopes)
    - name: "members:read"
      description: "View organization members"
    - name: "members:invite"
      description: "Invite new members to organization"
    - name: "members:update"
      description: "Update member roles and permissions"
    - name: "members:remove"
      description: "Remove members from organization"
    - name: "members:suspend"
      description: "Suspend member access"

    # Billing Management (4 scopes)
    - name: "billing:read"
      description: "View billing information and invoices"
    - name: "billing:manage"
      description: "Manage billing, subscriptions, and payment methods"
    - name: "billing:export"
      description: "Export billing data and invoices"
    - name: "billing:admin"
      description: "Full billing administration"

    # Settings Management (6 scopes)
    - name: "settings:read"
      description: "View organization settings"
    - name: "settings:write"
      description: "Update organization settings"
    - name: "settings:export"
      description: "Export organization settings"
    - name: "settings:import"
      description: "Import organization settings"
    - name: "settings:security"
      description: "Manage security settings (SSO, 2FA, IP whitelist)"
    - name: "settings:admin"
      description: "Advanced settings administration"

    # Roles & Permissions (5 scopes)
    - name: "roles:read"
      description: "View roles and their permissions"
    - name: "roles:write"
      description: "Create and update custom roles"
    - name: "roles:delete"
      description: "Delete custom roles"
    - name: "roles:assign"
      description: "Assign roles to members"
    - name: "permissions:read"
      description: "View available permissions"

    # Projects Management (4 scopes)
    - name: "projects:read"
      description: "View projects and their details"
    - name: "projects:write"
      description: "Create and update projects"
    - name: "projects:delete"
      description: "Delete projects"
    - name: "projects:admin"
      description: "Advanced project administration"

    # API Keys Management (4 scopes)
    - name: "api-keys:read"
      description: "View API keys (excluding full values)"
    - name: "api-keys:create"
      description: "Create new API keys"
    - name: "api-keys:update"
      description: "Update API key settings"
    - name: "api-keys:delete"
      description: "Delete API keys"

    # Integrations Management (3 scopes)
    - name: "integrations:read"
      description: "View configured integrations"
    - name: "integrations:configure"
      description: "Configure integrations (webhooks, alerts)"
    - name: "integrations:delete"
      description: "Delete integrations"

    # Audit Logs (2 scopes)
    - name: "audit-logs:read"
      description: "View audit logs and security events"
    - name: "audit-logs:export"
      description: "Export audit log data"

    # Webhooks (4 scopes)
    - name: "webhooks:read"
      description: "View webhook configurations"
    - name: "webhooks:create"
      description: "Create webhook endpoints"
    - name: "webhooks:update"
      description: "Update webhook configurations"
    - name: "webhooks:delete"
      description: "Delete webhooks"

    # Notifications (2 scopes)
    - name: "notifications:read"
      description: "View notification settings"
    - name: "notifications:configure"
      description: "Configure notification preferences"

    # ========================================
    # PROJECT-LEVEL SCOPES (20 scopes)
    # ========================================

    # Traces Management (5 scopes)
    - name: "traces:read"
      description: "View traces and observations"
    - name: "traces:create"
      description: "Create and ingest traces"
    - name: "traces:delete"
      description: "Delete traces and observations"
    - name: "traces:export"
      description: "Export trace data"
    - name: "traces:share"
      description: "Share traces publicly"

    # Analytics & Dashboards (4 scopes)
    - name: "analytics:read"
      description: "View analytics and metrics"
    - name: "analytics:export"
      description: "Export analytics data"
    - name: "analytics:dashboards"
      description: "Create and manage custom dashboards"
    - name: "analytics:admin"
      description: "Advanced analytics administration"

    # Models Management (3 scopes)
    - name: "models:read"
      description: "View AI model configurations"
    - name: "models:configure"
      description: "Configure AI models and routing"
    - name: "models:admin"
      description: "Advanced model administration"

    # Providers Management (2 scopes)
    - name: "providers:read"
      description: "View AI provider configurations"
    - name: "providers:configure"
      description: "Configure AI providers and credentials"

    # Cost Management (2 scopes)
    - name: "costs:read"
      description: "View cost analytics and usage"
    - name: "costs:export"
      description: "Export cost and usage data"

    # Prompts Management (4 scopes)
    - name: "prompts:read"
      description: "View prompt templates"
    - name: "prompts:create"
      description: "Create new prompt templates"
    - name: "prompts:update"
      description: "Update prompt templates"
    - name: "prompts:delete"
      description: "Delete prompt templates"

  roles:
    # ========================================
    # ORGANIZATION-LEVEL ROLES (4 roles)
    # ========================================

    # Owner: Full access (63 scopes)
    - name: "owner"
      description: "Full access to organization and all its resources"
      scope_type: "organization"
      permissions:
        # Organization scopes (40)
        - "organizations:read"
        - "organizations:write"
        - "organizations:delete"
        - "organizations:admin"
        - "members:read"
        - "members:invite"
        - "members:update"
        - "members:remove"
        - "members:suspend"
        - "billing:read"
        - "billing:manage"
        - "billing:export"
        - "billing:admin"
        - "settings:read"
        - "settings:write"
        - "settings:export"
        - "settings:import"
        - "settings:security"
        - "settings:admin"
        - "roles:read"
        - "roles:write"
        - "roles:delete"
        - "roles:assign"
        - "permissions:read"
        - "projects:read"
        - "projects:write"
        - "projects:delete"
        - "projects:admin"
        - "api-keys:read"
        - "api-keys:create"
        - "api-keys:update"
        - "api-keys:delete"
        - "integrations:read"
        - "integrations:configure"
        - "integrations:delete"
        - "audit-logs:read"
        - "audit-logs:export"
        - "webhooks:read"
        - "webhooks:create"
        - "webhooks:update"
        - "webhooks:delete"
        - "notifications:read"
        - "notifications:configure"
        # Project scopes (20)
        - "traces:read"
        - "traces:create"
        - "traces:delete"
        - "traces:export"
        - "traces:share"
        - "analytics:read"
        - "analytics:export"
        - "analytics:dashboards"
        - "analytics:admin"
        - "models:read"
        - "models:configure"
        - "models:admin"
        - "providers:read"
        - "providers:configure"
        - "costs:read"
        - "costs:export"
        - "prompts:read"
        - "prompts:create"
        - "prompts:update"
        - "prompts:delete"

    # Admin: All except delete org/projects (61 scopes)
    - name: "admin"
      description: "Administrative access to organization resources (no delete org/projects)"
      scope_type: "organization"
      permissions:
        # Organization scopes (38 - no delete org/projects)
        - "organizations:read"
        - "organizations:write"
        - "organizations:admin"
        - "members:read"
        - "members:invite"
        - "members:update"
        - "members:remove"
        - "members:suspend"
        - "billing:read"
        - "billing:manage"
        - "billing:export"
        - "billing:admin"
        - "settings:read"
        - "settings:write"
        - "settings:export"
        - "settings:import"
        - "settings:security"
        - "settings:admin"
        - "roles:read"
        - "roles:write"
        - "roles:delete"
        - "roles:assign"
        - "permissions:read"
        - "projects:read"
        - "projects:write"
        - "projects:admin"
        - "api-keys:read"
        - "api-keys:create"
        - "api-keys:update"
        - "api-keys:delete"
        - "integrations:read"
        - "integrations:configure"
        - "integrations:delete"
        - "audit-logs:read"
        - "audit-logs:export"
        - "webhooks:read"
        - "webhooks:create"
        - "webhooks:update"
        - "webhooks:delete"
        - "notifications:read"
        - "notifications:configure"
        # Project scopes (20 - all project scopes)
        - "traces:read"
        - "traces:create"
        - "traces:delete"
        - "traces:export"
        - "traces:share"
        - "analytics:read"
        - "analytics:export"
        - "analytics:dashboards"
        - "analytics:admin"
        - "models:read"
        - "models:configure"
        - "models:admin"
        - "providers:read"
        - "providers:configure"
        - "costs:read"
        - "costs:export"
        - "prompts:read"
        - "prompts:create"
        - "prompts:update"
        - "prompts:delete"

    # Developer: Dev workflows (30 scopes)
    - name: "developer"
      description: "Development access to projects, analytics, and API keys"
      scope_type: "organization"
      permissions:
        # Organization scopes (10 - read-only org access)
        - "organizations:read"
        - "settings:read"
        - "projects:read"
        - "projects:write"
        - "api-keys:read"
        - "api-keys:create"
        - "api-keys:update"
        - "api-keys:delete"
        - "integrations:read"
        - "notifications:read"
        # Project scopes (20 - full project access)
        - "traces:read"
        - "traces:create"
        - "traces:delete"
        - "traces:export"
        - "traces:share"
        - "analytics:read"
        - "analytics:export"
        - "analytics:dashboards"
        - "analytics:admin"
        - "models:read"
        - "models:configure"
        - "models:admin"
        - "providers:read"
        - "providers:configure"
        - "costs:read"
        - "costs:export"
        - "prompts:read"
        - "prompts:create"
        - "prompts:update"
        - "prompts:delete"

    # Viewer: Read-only (15 scopes)
    - name: "viewer"
      description: "Read-only access to organization resources"
      scope_type: "organization"
      permissions:
        # Organization scopes (7 - read-only)
        - "organizations:read"
        - "settings:read"
        - "projects:read"
        - "api-keys:read"
        - "integrations:read"
        - "audit-logs:read"
        - "notifications:read"
        # Project scopes (8 - read-only)
        - "traces:read"
        - "analytics:read"
        - "models:read"
        - "providers:read"
        - "costs:read"
        - "prompts:read"

  memberships:
    # Organization memberships with roles
    - user_email: "admin@brokle.ai"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "brokle-tech"

    - user_email: "developer@brokle.ai"
      role_name: "developer"
      scope_type: "organization"
      organization_slug: "brokle-tech"

    - user_email: "demo@example.com"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "demo-org"

    - user_email: "test@startup.com"
      role_name: "owner"
      scope_type: "organization"
      organization_slug: "test-startup"

projects:
  - name: "AI Gateway"
    description: "Primary AI gateway and routing service"
    organization_slug: "brokle-tech"
    environments:
      - name: "Development"
        slug: "dev"
      - name: "Staging"
        slug: "staging"
      - name: "Production"
        slug: "prod"

  - name: "Analytics Platform"
    description: "AI analytics and observability platform"
    organization_slug: "brokle-tech"
    environments:
      - name: "Development"
        slug: "dev"
      - name: "Production"
        slug: "prod"

  - name: "Demo Application"
    description: "Demo application showcasing Brokle capabilities"
    organization_slug: "demo-org"
    environments:
      - name: "Demo"
        slug: "demo"
      - name: "Production"
        slug: "prod"

  - name: "Test Project"
    description: "Simple test project for validation"
    organization_slug: "test-startup"
    environments:
      - name: "Test"
        slug: "test"

api_keys:
  - name: "Development API Key"
    organization_slug: "brokle-tech"
    project_name: "AI Gateway"
    environment_name: "Development"
    rate_limit_per_minute: 1000
    rate_limit_per_hour: 10000
    rate_limit_per_day: 100000
    scopes:
      - "ai:completions"
      - "ai:embeddings"
      - "analytics:read"
    allowed_ips: []

  - name: "Production API Key"
    organization_slug: "brokle-tech"
    project_name: "AI Gateway"
    environment_name: "Production"
    rate_limit_per_minute: 5000
    rate_limit_per_hour: 50000
    rate_limit_per_day: 1000000
    scopes:
      - "ai:completions"
      - "ai:embeddings"
      - "analytics:read"
    allowed_ips: ["203.0.113.0/24", "198.51.100.0/24"]

  - name: "Demo API Key"
    organization_slug: "demo-org"
    project_name: "Demo Application"
    environment_name: "Demo"
    rate_limit_per_minute: 100
    rate_limit_per_hour: 1000
    rate_limit_per_day: 10000
    scopes:
      - "ai:completions"
    allowed_ips: []

  - name: "Test API Key"
    organization_slug: "test-startup"
    project_name: "Test Project"
    environment_name: "Test"
    rate_limit_per_minute: 60
    rate_limit_per_hour: 500
    rate_limit_per_day: 5000
    scopes:
      - "ai:completions"
    allowed_ips: []

onboarding_questions:
  - step: 1
    question_type: "single_choice"
    title: "What's your primary role?"
    description: "This helps us customize your experience"
    is_required: true
    options:
      - "Developer"
      - "Product Manager"
      - "Data Scientist"
      - "DevOps Engineer"
      - "CEO/Founder"
      - "Other"
    display_order: 1
    is_active: true

  - step: 2
    question_type: "multiple_choice"
    title: "Which AI providers do you currently use?"
    description: "Select all that apply"
    is_required: true
    options:
      - "OpenAI"
      - "Anthropic"
      - "Google AI"
      - "Cohere"
      - "Hugging Face"
      - "Azure OpenAI"
      - "AWS Bedrock"
      - "None yet"
    display_order: 2
    is_active: true

  - step: 3
    question_type: "single_choice"
    title: "What's your organization size?"
    description: "Help us understand your team"
    is_required: true
    options:
      - "Just me"
      - "2-10 people"
      - "11-50 people"
      - "51-200 people"
      - "200+ people"
    display_order: 3
    is_active: true

  - step: 4
    question_type: "text"
    title: "What's your primary use case for AI?"
    description: "Tell us about your main AI application (optional)"
    is_required: false
    options: []
    display_order: 4
    is_active: true

  - step: 5
    question_type: "single_choice"
    title: "How did you hear about Brokle?"
    description: "Help us improve our outreach"
    is_required: false
    options:
      - "Search engine"
      - "Social media"
      - "Word of mouth"
      - "Conference/Event"
      - "Blog/Article"
      - "GitHub"
      - "Other"
    display_order: 5
    is_active: true
